include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DoubleTapDotPrefs
DoubleTapDotPrefs_FILES = DTDRootListController.m
DoubleTapDotPrefs_FRAMEWORKS = UIKit Foundation
DoubleTapDotPrefs_PRIVATE_FRAMEWORKS = Preferences
DoubleTapDotPrefs_INSTALL_PATH = /Library/PreferenceBundles
DoubleTapDotPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
